Feat: Add Docker compose to run local enviroment
SHIV5T3R/CO-DE pull request #28
Opened 2023-08-12 09:23 UTC by blackmouse572

Docker compose will run
- Frontend at `3000` port
- Backend at `5000` port
- Mongodb at `27017` port
- Redis at `6397` port

You can also config the env at `compose.yml` otherwise, the default values:
      - MONGO_INITDB_DATABASE=code
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

2023-08-16 19:14 UTC, believemanasseh reviewed
I'd suggest we maintain two docker-compose files (one for development, the other for production). And also we can make use of bash scripts to start dev and prod servers instead of using the CMD in the dockerfile. Just my two cents!

2023-08-16 19:14 UTC, believemanasseh commented on backend/Dockerfile
To make it more dynamic (i.e. including production support), how about you RUN a bash script instead that handles both cases (dev and prod)? Then we could have two docker-compose files for both dev and production.

2023-08-16 19:14 UTC, believemanasseh commented on frontend/Dockerfile
This setup is supposedly for production builds? Actually, since we've not actually discussed production deployment, to run the development server, you need the `npm run dev` command and you don't need to run builds either. Finally, I'm trying to understand the folder structure of the docker container here. I'd assume the actual /src (source code) folder would be nested in a root /src folder specified as the WORKDIR? I'd think you'd maintain the same pattern you used for the backend dockerfile.

2023-08-21 05:38 UTC, blackmouse572 commented on frontend/Dockerfile
- the `WORKDIR` name can be anything so i take /src as common name. 
- running prod version of project on docker is a best practice. In another hand, mostly docker is support for another side of developer to run locally instead of actually download React/Python. So i decided to use prod as default.

2023-08-21 05:40 UTC, blackmouse572 commented on backend/Dockerfile
Too much work for simple task. According to my exp, I never have to use dev environment for docker image. They are usually a pre-production version already since I only need a local version without installing anything and not modifying the src code.

2023-08-21 07:07 UTC, believemanasseh commented on backend/Dockerfile
Are you saying when working on our host machine, we shouldn't use docker? Because the purpose of creating multiple docker compose files is to spin up containers in both local environment

2023-08-21 07:09 UTC, believemanasseh commented on frontend/Dockerfile
If you're saying we shouldn't have to use containers when developing locally, then that's fine. Other than that, I don't see reasons why we should be using prod builds or server locally

2023-08-21 07:11 UTC, believemanasseh commented on frontend/Dockerfile
Also, I know the WORKDIR can be anything. I'm only concerned about the nesting. From what I understand, it becomes src (workdir) -> src (actual source code file in frontend folder) — hence the nesting.

2023-09-07 19:31 UTC, joshua-mo-143 commented on backend/Dockerfile
What exactly is the difference between dev and prod at the moment? It seems like we could reasonably run a prod setup locally. The main difference as I see it at the moment would be the secrets/database connections, which we can theoretically just set in the config anyway before spinning everything up.

2023-09-07 19:39 UTC, joshua-mo-143 commented on frontend/Dockerfile
`WORKDIR` should probably be `app`.

I think the main thing at the moment is that if there isn't actually any consequences for switching to a production build, then it's primarily arbitrary.

2023-09-07 20:41 UTC, believemanasseh commented on backend/Dockerfile
I think I agree with this really. I was thinking we might want to run the containers locally with a dev server and whatnot (but I guess there isn't much point). Our main goal is consistency between dev and prod, and running prod only seems to achieve that.

2023-09-07 20:54 UTC, believemanasseh requested changes

2023-09-07 20:54 UTC, believemanasseh commented on frontend/Dockerfile
I also thought the /src nesting was weird.

Also, seems there's no problem using only prod builds in docker then. I guess since prod is our main focus, we should be able to test in the same environment while developing. But the PR still needs to be modified though. It currently uses the `serve` package to serve prod builds but this dependency is not in the package.json. The `npm run serve` command would not also work for similar reasons.

2023-09-07 20:54 UTC, believemanasseh commented on backend/Dockerfile
But this dockerfile still uses a dev flask server though. If it's a prod container, then we need suitable servers.

2023-10-30 17:31 UTC, zatoa commented
I would setup .env.examples and pull these into docker-compose instead of hard coding.

2023-10-30 17:39 UTC, zatoa commented
Usually I've only used docker-compose locally in dev to setup the supporting services such as redis,postgresql,nginx etc. It might be that someone just wants these supporting services without building the local Dockerfiles. Two compose files might be useful depending how prod is deployed..

Popping a docker-compose up/down script in the package.json might be useful

2023-11-02 09:28 UTC, blackmouse572 commented
> Usually I've only used docker-compose locally in dev to setup the supporting services such as redis,postgresql,nginx etc. It might be that someone just wants these supporting services without building the local Dockerfiles. Two compose files might be useful depending how prod is deployed..
> 
> Popping a docker-compose up/down script in the package.json might be useful

That good idea. Could you help me add this to script and embed env ?

2023-11-05 02:23 UTC, believemanasseh commented
> Usually I've only used docker-compose locally in dev to setup the supporting services such as redis,postgresql,nginx etc. It might be that someone just wants these supporting services without building the local Dockerfiles. Two compose files might be useful depending how prod is deployed..
> 
> Popping a docker-compose up/down script in the package.json might be useful

What do you mean by "popping a docker-compose up/down script in the package.json"? 

Also in this context, I'd assume we could use something like docker swarm to unify these multiple docker compose environments. cc: @joshua-mo-143

2024-02-04 12:48 UTC, zatoa commented
@blackmouse572 @believemanasseh This is now a duplicate/stale/old PR?

2024-02-04 14:13 UTC, believemanasseh commented
> @blackmouse572 @believemanasseh This is now a duplicate/stale/old PR?

Yeah

2024-02-06 20:08 UTC, closed without merging